"""Shared session-state defaults for the Streamlit UI."""

from __future__ import annotations


def build_app_defaults(
    *,
    is_synthetic_mode: bool,
    demo_story: str,
    scenario_pack_choice: str,
) -> dict[str, object]:
    return {
        "graph_data": None,
        "shock_result": None,
        "agent_messages": [],
        "pos": None,
        "current_wave": -1,
        "sector_dict": None,
        "tickers": None,
        "chat_history": [],
        "comparison": None,
        "sel_date": "2023-03-13" if is_synthetic_mode else None,
        "sel_ticker": "JPM",
        "sel_shock": 50,
        "sel_model": "debtrank",
        "sel_threshold": 0.35 if is_synthetic_mode else 0.5,
        "agent_mode": True,
        "agent_timeout_sec": 35,
        "agent_strategy": "simple",
        "high_quality_mode": False,
        "gpt_for_parseable_queries": False,
        "agent_diagnostic": "",
        "last_run_metrics": None,
        "agent_response_cache": {},
        "demo_mode": False,
        "demo_story": demo_story,
        "pending_chat_query": "",
        "run_trace": None,
        "run_trace_history": [],
        "persist_trace_logs": True,
        "show_explainability": True,
        "eval_results": None,
        "judge_unlocked": False,
        "judge_unlock_error": "",
        "gpt_rate_events": [],
        "gpt_calls_total_session": 0,
        "gpt_rate_limit_hits": 0,
        "risk_profile": "balanced",
        "scenario_pack_choice": scenario_pack_choice,
        "last_structured_payload": None,
        "run_quality": None,
        "scenario_eval_results": None,
        "compare_rows_local": [],
        "compare_meta": {},
        "gpt_fail_streak": 0,
        "gpt_circuit_open_until": 0.0,
        "run_cancel_requested": False,
        "rag_last_docs": [],
        "judge_kpis": {},
        "critic_auto_repair": True,
        "evidence_gate_strict": True,
        "use_session_memory": True,
        "session_decisions": [],
        "commander_results": None,
        "autonomous_results": None,
        "portfolio_text": "",
        "auto_portfolio_n": 5,
        "portfolio_copilot": None,
        "latest_policy_plan": [],
        "latest_executor_log": [],
        "last_agentic_action": "",
        "agentic_ops_cache": {},
        "full_demo_last_run": None,
        "outlook_report": None,
        "outlook_joined": None,
        "outlook_joined_by_model": None,
        "outlook_metric": "density",
        "outlook_model": "best",
        "outlook_focus_date": None,
        "outlook_sync_shock_date": True,
        "outlook_shock_bundle": None,
        "outlook_compare_bundle": None,
        "outlook_shock_date": None,
        "outlook_shock_ticker": "JPM",
        "outlook_shock_pct": 40,
        "outlook_shock_model": "debtrank",
        "outlook_shock_threshold": 0.35 if is_synthetic_mode else 0.45,
        "outlook_shock_seed_mode": "ticker",
        "outlook_shock_sector": "Financials",
        "outlook_compare_enabled": False,
        "outlook_compare_ticker": "GS",
        "outlook_compare_model": "linear_threshold",
        "outlook_compare_shock_pct": 30,
        "outlook_policy_intervention": "none",
        "outlook_train_end": None,
        "outlook_test_end": None,
        "outlook_walk_step_days": 20,
        "outlook_walk_horizon_days": 20,
        "outlook_alpha": 1.0,
        "outlook_engine_version": "",
    }
